package LeetCode;

/*
https://leetcode.com/problems/find-the-difference/
Easy. Hash Table, Bit Manipulation.

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s
and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class _389_FindTheDifference {

    public static char findTheDifference(String s, String t) {
        if (s == null || t == null || s.length() + 1 != t.length()) throw new IllegalArgumentException();
        else if (s.length() == 0) return t.charAt(0);

        char res = 0;
        for (char c : s.toCharArray()) {
            res ^= c;
        }
        for (char c : t.toCharArray()) {
            res ^= c;
        }
        return res;
    }
}
